src/test/java/scala_maven/MiscTest.java

This is related to this issue: #186
Also, if interested, I could create a PR that included a Maven Enforcer Rule to fail the build sooner.

Improve test failure message for wrong JDK (> 7).

---

src/it/includesExcludes/pom.xml
src/it/off-test_scaladoc2_onMultiModules/pom.xml
src/it/test1/pom.xml
src/it/test_custom_outputdir/pom.xml
src/it/test_goal_site/pom.xml
src/it/test_scalaHome/pom.xml

Tested by running mvn integration-test, which failed without these
changes.
See
https://cwiki.apache.org/confluence/display/MAVEN/AetherClassNotFound
for details on what this upgrade does and what was broken when I ran
the ITs.

Upgrade maven-site-plugin in ITs to 3.3 so that ITs pass with Maven 3.3.3

---

pom.xml
src/main/java/sbt_inc/SbtIncrementalCompiler.java
src/main/java/scala_maven/ScalaCompilerSupport.java
src/main/java/scala_maven_executions/JavaMainCallerByFork.java
src/main/java/util/JavaHomeLocator.java
src/main/java/util/JavaLocator.java

I was hitting an issue where Zinc was using Java 7 (which was what launched Maven,) despite toolchains specifying Java 8.  This change has us look up the desired Java version through a few steps of resolution, and then passes that to Zinc.
The ITs passed, though I had to also have https://github.com/davidB/scala-maven-plugin/pull/190 for them to pass locally.  Ideally I would merge https://github.com/davidB/scala-maven-plugin/pull/190 first to avoid mistakes.

Zinc - Toolchains support

---

pom.xml
src/main/java/scala_maven/ScalaMojoSupport.java

* `pom.xml`
* Added `maven-compat` dependency which allows to usage of Maven 2 features
with Maven 3.
* Removed Maven 2 dependency.
* `src/main/java/scala_maven/ScalaMojoSupport.java`
* Removed wildcard type that was used for the Maven 2 dependency that was
removed. Replaced it with the correct generic type, as required by
`maven-compat`.

Use `maven-compat` for the Maven 2 features.

---

src/main/java/scala_maven/ScalaConsoleMojo.java
src/main/java/scala_maven/ScalaMojoSupport.java

Derive the JLine dependency from the Scala compiler. This fixes #196 and allows use of `scala:console` with scala 2.12.
**Important**, this PR requires the changes introduced in #205. That PR should be reviewed first. If there are changes made as a result of the review of #205, I'll port them into this PR if/when that PR is merged.
Closes #196 
* `src/main/java/scala_maven/ScalaMojoSupport.java`
* Added `static` values for a couple `String` values used internally in the
class, namely "pom" and "jar". Updated usage instances of strings in the
class to use the constants.
* Added method to resolve the `Artifact` for the `scala-compiler`.
* Added more general overloads for `resolveDependencyArtifacts` allowing for
specification of various artifact filters. Changed the resolution method to
use …

Fix scala console212

---

pom.xml
src/test/java/scala_maven/MiscTest.java

This will allow building this project with JDK 8 (the only version that is not EOL without an Oracle contract), while still supporting usage by those institutions that do have an aforementioned extended service contract.
* `pom.xml`
* Added `target` to the `maven-compiler-plugin` and set to `1.6`. This should
allow us to build with JDK 1.8 and still support 1.6 clients, keeping in
mind we can not use Java Standard Library 1.8 exclusive symbols.
* `src/test/java/scala_maven/MiscTest.java`
* Removed test that fails if you are using JDK > 7.
Note, I have successfully tested the plugin with against the invoker tests using JDK 1.6 using the output of this change.

Ask java compiler to generate 1.6 compatible bytecode

---

pom.xml

Problem:
`integration-tests` profile has two activations: `activeByDefault` and `maven.tests.skip!=true`. Maven activates a profile when at least one activation condition is true. Thus this profile will be active regardless of the `maven.tests.skip` property.
Solution:
Remove `activeByDefault` section. `maven.tests.skip!=true` is enough.

Make it possible to deactivate `integration-tests` profile

---

src/main/java/util/JavaLocator.java
src/test/java/util/JavaLocatorTest.java

`System.getProperty("java.home")` return the path to the JDK and cannot be override. 
`JAVA_HOME` should be checked before this to allow users to actually affect the path sent to the zinc server, other than using the toolchain plugin.
This fixes issue #221.

Check JAVA_HOME before java.home to locate JDK home

---

src/main/java/scala_maven/ScalaConsoleMojo.java

I added this line when debugging b673367a0b2aaee70d835811b8d4a0612da2de5c, but I neglected to remove it before making the commit.

Removed bad warning log.

---

pom.xml

The latest version of zinc is now 0.3.15 and is fully compatible with the previous one.

Bump zinc version to 0.3.15

---

README.md

See #226: update readme.md
1. update plugin title
2. reference similar plugins
3. remove broken donate link
4. remove broken bitdeli link

See #226: update readme.md

---

pom.xml
src/main/java/scala_maven/AddSourceMojo.java
src/main/java/scala_maven/Launcher.java
src/main/java/scala_maven/ScalaCompileMojo.java
src/main/java/scala_maven/ScalaCompilerSupport.java
src/main/java/scala_maven/ScalaConsoleMojo.java
src/main/java/scala_maven/ScalaContinuousCompileMojo.java
src/main/java/scala_maven/ScalaContinuousTestMojo.java
src/main/java/scala_maven/ScalaDocJarMojo.java
src/main/java/scala_maven/ScalaDocMojo.java
src/main/java/scala_maven/ScalaHelpMojo.java
src/main/java/scala_maven/ScalaMojoSupport.java
src/main/java/scala_maven/ScalaRunMojo.java
src/main/java/scala_maven/ScalaScriptMojo.java
src/main/java/scala_maven/ScalaSourceMojoSupport.java
src/main/java/scala_maven/ScalaTestCompileMojo.java

The two main reasons for this move:
1. It is partially checked by the compiler
2. It makes interoperability easier, as the Java annotations were preserved in the classfiles whereas the javadoc-annoations were not.
E.g. The bloop project has a maven plugin which inherits from some base classes of this plugin to read it's configuration.
After this change, the maven plugin build just works, but before, it couldn't see any `@parameter` and `@component` comments, which is a real pain.
Cutting a release after merge would be very much appreciated.

Migrated javadoc-style annotation to Maven Plugin Annotations.

---

src/main/java/scala_maven/ScalaDocJarMojo.java

Beginning with d9f45d0, the doc-jar goal (ScalaDocJarMojo) was not passing a classpath to scaladoc. When running on Java 8, scaladoc reported errors wherever any symbol from a dependency is mentioned (e.g. “object log4s is not a member of package org”, even though log4s is supposed to be on the classpath). When running on Java 10, scaladoc suffered an immediate fatal error instead (“object scala in compiler mirror not found”).
Here's an example args file, demonstrating the problem:
```
-Xlint
-doc-format:html
-doc-title
"Find install4j Library 1.1-SNAPSHOT API"
-d
"C:\Users\[user]\Documents\find-install4j\target\site\scaladocs"
"C:\Users\[user]\Documents\find-install4j\src\main\scala\com\valuadder\util\findinstall4j\ComponentFinder.scala" …
```

`doc-jar` passes no classpath to scaladoc

---

pom.xml
src/it/test_scaladoc_compiler_plugins/invoker.properties
src/it/test_scaladoc_compiler_plugins/pom.xml
src/it/test_scaladoc_compiler_plugins/src/main/scala/MyClass.scala
src/it/test_scaladoc_compiler_plugins/validate.groovy
src/main/java/scala_maven/ScalaDocMojo.java

I have been unable to use `kind-projector` in much of my code while still producing scaladoc because the `-Xplugin` option has not been included when invoking scaladoc. This means that the build fails, so I was left with the choice of having type aliases or not generating documentation. 
This PR fixes this issue by adding the compiler plugin arguments to the scaladoc execution. An integration test has been added to verify that it works. Note that I used `kind-projector` in the sample project, which required adding a new property (`scala.version.binary`) to the top-level `pom.xml` that tracks the latest binary-compatible version for appending to any library artifacts.

Add compiler plugins to scaladoc execution

---

.travis.yml
pom.xml
src/main/java/sbt_inc/SbtIncrementalCompiler.java
src/main/java/sbt_inc/SbtLogger.java
src/main/java/scala_maven/ScalaCompilerSupport.java
src/main/java/scala_maven/ScalaMojoSupport.java
src/main/java/scala_maven/VersionNumber.java

There's most likely lots of cleaning up, but you can have a look.

First take at upgrading Zinc

---

src/main/java/scala_maven/ScalaContinuousCompileMojo.java
src/main/java/scala_maven/ScalaMojoSupport.java

This API change: https://github.com/davidB/scala-maven-plugin/commit/e2ce8b3759a581f32593a56bac100a1a51a68966#diff-2660d2ba8fa58383b0f754f4a4155f71L25 changing the members from protected to private kinda messes up: https://github.com/scalacenter/bloop/blob/master/integrations/maven-bloop/src/main/java/scala_maven/ExtendedScalaContinuousCompileMojo.java
`session` was also needed in `ScalaMojoSupport`
I've verified I can compile `bloop` with these changes.
Regards,
Eric

Partial revert of e2ce8b3759a581f32593a56bac100a1a51a68966 protected => private API changes for bloop/other 3rd party apps

---

pom.xml
src/main/java/sbt_inc/SbtIncrementalCompiler.java

Motivation:
We use precompile Zinc compiler-bridge.
Alas, `org.scala-sbt:compiler-bridge_2.13:1.2.5` as deployed on maven central is actually compiled against Scala 2.13.0-M2, so it crashes when trying to compile with Scala 2.13.0 as the Collection API was revamped since then.
Modification:
* Upgrade Zinc 1.3.0-M7 whose compiler-bridge is properly compiled against Scala 2.13.0.
* minor previousResult configuration clean up
Result:
scala-maven-plugin now supports Scala 2.13 (stable).

Upgrade Zinc 1.3.0-M7, support Scala 2.13.0, close #346

---

src/main/java/sbt_inc/SbtIncrementalCompiler.java
src/main/java/scala_maven/ScalaCompilerSupport.java
src/main/java/scala_maven/ScalaMojoSupport.java

* Stop using IncrementalCompilerImpl, use ZincUtil.defaultIncrementalCompiler that returns an IncrementalCompiler and directly create other components (compiler, setup, emptyPreviousResult) instead of using IncrementalCompilerImpl methods.
* Move SbtIncrementalCompiler constants to ScalaCompilerSupport where they are actually used
* Move getCompilerBridgeJar to ScalaCompilerSupport where it's actually used

Misc incremental compiler clean up

---

src/main/java/scala_maven/ScalaMojoSupport.java

This PR proposes to allow to omit `-target` and `-source` options in javac.
```
[debug] Forking javac: /.../bin/javac @/.../argfile
[error] error: option -source cannot be used together with --release
[error] error: option -target cannot be used together with --release
[error] Usage: javac <options> <source files>
[error] use --help for a list of possible options
[debug] javac returned exit code: 2
```
I am trying to cross-compile with `--release` option in JDK 11; however, due to added `-source` and `-target`, seems unable to do it.
_Note that_ if corresponding properties are not set, it seems setting default values to the properties (see https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html) instead of setting it as `null`. So there look no way to set `target` and …

Allow to omit -target and -source options in javac

---

src/main/java/scala_maven/ScalaCompileMojo.java

Fix implemented as outlined in the [issue](https://github.com/davidB/scala-maven-plugin/issues/379). Test in an Apache James subproject:
```
C:\ws414\james\server\task\task-api>mvn scala:compile -DoutputDir=target-scala
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< org.apache.james:james-server-task-api >---------------
[INFO] Building Apache James :: Server :: Task :: API 3.5.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
(...)
[INFO] Compiling 2 Scala sources and 5 Java sources to 
C:\ws414\james\server\task\task-api\target-scala ...
```
Testing default behaviour:
```
C:\ws414\james\server\task\task-api>mvn scala:compile
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< org.apache.james:james-server-task-api …
```

Issue-379: Can't use user property outputDir from the command line

---

src/main/java/sbt_inc/SbtLogger.java

To avoid a double log-level prefix to all messages, remove the one coming in
from Sbt.  The one that Maven generates will do fine.

Remove log-level prefix from incoming Sbt log messages

---

src/site/xdoc/example_incremental.xml.vm
src/site/xdoc/faq.xml.vm

- Update references to Zinc to point to the currently maintained sbt Zinc project.
- Remove documentation on using Zinc server, as support for this was removed from the plugin in version 4.0.0
There are some other issues with the Incremental Compile documentation, such as incremental being enabled by default now in version 4.0.0. But I'm not familiar enough with this project to update that documentation any further.

Update Zinc information in documentation site

---

src/site/xdoc/example_incremental.xml.vm

Since scala-maven-plugin v4.0.0 [2], the incremental compilation is enabled by default [2] and remove the support of zinc stand-alone version (aka [typesafe/zinc](https://github.com/typesafehub/zinc)) [3].
This patch updates Zinc and `reompileMode` related decription.
Related: 
[1] https://github.com/davidB/scala-maven-plugin/pull/408
[2] https://github.com/davidB/scala-maven-plugin/commit/0f01f2fe37aaadbefb02fb713d469dbd10acf8b1
[3] https://github.com/davidB/scala-maven-plugin/pull/321

Update zinc related description

---

README.md

Hi!
As discussed in #486, I've make a maven plugin that simply delegates to SBT. There are some pros and cons with this approach, but it seems like the best way to use Scala.js and other advanced SBT features with maven.
https://github.com/AugustNagro/sbt-delegate-maven-plugin
Cheers,
August

Add Sbt-Delegate-Maven-Plugin to Similar Plugins

---

pom.xml
src/main/java/sbt_inc/SbtIncrementalCompiler.java

In particular, exclude log4j 2 we don't use, so that it's not even in the classpath.

Zinc exclusions

---

src/main/java/scala_maven/ScalaCompilerLoader.java
src/main/java/scala_maven/ScalaCompilerSupport.java

Motivation:
Jigsaw has changed the behavior of ClassLoaders.
For some reason, ScalaCompilerLoader with a null parent is able to find JDK classes on Java 8 but not on Java 11.
Modification:
Make the parent the root loader.
Result:
We can compile macros with Java 11.

Fix incremental compiler not being able to find JDK classes when compiler macros with Java 11, close #502

---

src/main/java/sbt_inc/SbtIncrementalCompiler.java

Remove the FileConverter, it seems to break things.

Fix incremental compilation on Java 11+, close #600

---

src/main/java/util/JavaLocator.java
src/test/java/util/JavaLocatorTest.java

Motivation:
1. We should prefer the Java installation used to run maven to what's defined in JAVA_HOME
2. We should prefer JDK over JRE (for old versions that used to have one) as we need javac for compiling Java code in mixed projects
Modifications:
Resolve with the following chain:
* prefer toolchain if defined
* try to use "java.home" System prop to resolve a JDK, a JRE otherwise
* fall back to JAVA_HOME env var
Result:
Behavior consistent with `maven-compiler-plugin` and `org.codehaus.plexus.compiler.javac.JavacCompiler#getJavacExecutable`.
In particular:
* we no longer unexpectedly jump to a different Java install because JAVA_HOME env var is defined
* we no longer crash on Java 8 when trying to compile mixed projects and JAVA_HOME env var is undefined or doesn't point to a JDK.

Fix JavaLocator, close #619

---

src/main/java/scala_maven/ScalaMojoSupport.java

Motivation:
Scala 2.13.9 has deprecated -release in favor of -target, see https://www.scala-lang.org/news/2.13.9
As our default value for `release` is plugged onto `maven.compiler.target`, we end up with the default behavior of setting `-release:8` which now triggers a warning.
Modification:
Don't set `-release` is it's deprecated. If `target` is not explicitly defined, use the `release` value to set the `target` instead.
Result:
No more deprecation warning

Set -release instead of -target since Scala 2.13.9, close #646

---

src/main/java/scala_maven/ScalaMojoSupport.java
src/test/java/scala_maven/ScalaMojoSupportTest.java

Motivation:
We're generating `-release 1.8` for Scala 3. `1.8` is an illegal value for the `-release` option.
Moreover, `-release` has been renamed into `-java-output-version` in Scala 3.1.2.
Modifications:
* only generate `-target` if `-release` is not supported
* properly test for Scala 3
* generate `-java-output-version` instead of `-release` if Scala >+ 3.1.2
Result:
Correct compiler options with Scala 3.

fix Scalac options when using Scala 3, close #673

---

pom.xml

Maven 4 will no longer include the `org.apache.maven:maven-compat` library in the runtime.
Current versions of Maven 3 produce deprecation warnings related to this dependency in the plugin.
This PR removes the library as it does not appear to be used.

Remove deprecated dependency on maven-compat

---

src/main/java/sbt_inc/CompilerBridgeFactory.java

It was identified in https://github.com/davidB/scala-maven-plugin/issues/738 that a race condition could occur when building a project using multiple threads.
To mitigate the issue, I wrapped the installation of the compiler with a synchronized block on the Static instance.
As a result, if multiple threads try to install the compiler at the same time, only one thread will be able to do so. When they will get unlocked, it will check if the file was created meanwhile and if so, to will early return.

fix: Handle race conditions when getting the compiler bridge

---

pom.xml
src/test/java/util/JavaLocatorTest.java

system-rules no longer works with Java 17.
system-stubs-junit4 is a fork that works with all JDK versions.
https://www.baeldung.com/java-unit-testing-environment-variables

Replace system-rules with system-stubs-junit4

---

src/it/test_no_sources/validate.groovy
src/main/java/scala_maven/ScalaDocMojo.java
src/main/java/scala_maven/ScalaTestCompileMojo.java

Fixes support for Maven 4 immutable API
